---
title: "Introduction to RAWSmet"
author: "Mazama Science"
date: "Jan 30, 2022"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{RAWSmet}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  fig.width = 7,
  fig.height = 7
)
```

The **RAWSmet** R package is being developed for the USFS AirFire group to help 
modelers and scientists more easily work with weather data from RAWS stations 
across North America.

The package makes it easier to obtain data, perform analyses and generate 
reports. It includes functionality to:
  
* Access metadata and archival timeseries data from https://cefa.dri.edu/raws
* Access metadata and latest month timeseries data from https://raws.dri.edu
* Save and reload .rda versions of these in a `rawsDataDir`
* Determine which locations obtained from metadata are too close to be 
considered “unique” locations
* Convert between UTC and local timezones
* Apply various algorithms to the data 5rolling means, aggregation, _etc._
* Provide interactive timeseries and maps through RStudio’s Viewer pane
* Create a variety of publication ready maps and timeseries plots
