---
title: "September 2020 Oregon Wildfires"
author: "Eli Grosman, Mazama Science"
date: "September 18, 2020"
output: rmarkdown::html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background

## Assembling data
```{r assembleData, message = FALSE}
library(RAWSmet)

setRawsDataDir("~/Data/RAWS")

oregonMeta <- wrcc_loadMeta(stateCode = "OR")

filePath <- file.path(getRawsDataDir(), "stationList_OR.rda")

if ( file.exists(filePath) ) {
  
  stationList_OR <- get(load(filePath))
  
} else {
  
  stationList_OR <- list()
  counter <- 1

  for ( wrccID in oregonMeta$wrccID ) {

    message(sprintf("Working on %s (%d/%d)", wrccID, counter, nrow(oregonMeta)))

    # Keep going even if a particular station doesn't have data
    res <- try({

      stationTimeseriesObject <-
        wrcc_load(wrccID = wrccID, meta = oregonMeta, year = 2020) %>%
        raws_filterDate(
          startdate = MazamaCoreUtils::parseDatetime(20200831, timezone = "America/Los_Angeles"),
          enddate = MazamaCoreUtils::parseDatetime(20200914, timezone = "America/Los_Angeles"))

      stationList_OR[[wrccID]] <- stationTimeseriesObject
    }, silent = TRUE)

    counter <- counter + 1

  }

  save(stationList_OR, file = filePath)
    
}
```

## Locations with data
```{r oregonStations, message = FALSE}
wrccIDs <- names(stationList_OR)

meta <- oregonMeta %>% dplyr::filter(wrccID %in% wrccIDs)
RAWSmet::raws_leaflet(meta)
```

## Wind shift maps
```{r windShift, message = FALSE, echo = FALSE, fig.align = "center", fig.width = 10, fig.height = 10}
library(maps)

par(mfrow = c(2, 2))

maps::map('state', 'oregon', fill = FALSE, col = 'gray80')
title("Sept. 6th at noon")

for ( station in stationList_OR ) {
  data <- 
    station$data %>%
    dplyr::filter(
      datetime == MazamaCoreUtils::parseDatetime(2020090612, timezone = "America/Los_Angeles")
    )
  knots <- data$maxGustSpeed * 1.944
  addWindBarbs(
    station$meta$longitude, 
    station$meta$latitude, 
    knots, 
    data$maxGustDirection,
    circleSize = 0.5,
    circleFill = 'black',
    lineCol = 1,
    extraBarbLength = -0.2,
    lwd = 1.2
  )
}


maps::map('state', 'oregon', fill = FALSE, col = 'gray80')
title("Sept. 6th at midnight")

for ( station in stationList_OR ) {
  data <- 
    station$data %>%
    dplyr::filter(
      datetime == MazamaCoreUtils::parseDatetime(2020090700, timezone = "America/Los_Angeles")
    )
  knots <- data$maxGustSpeed * 1.944
  addWindBarbs(
    station$meta$longitude, 
    station$meta$latitude, 
    knots, 
    data$maxGustDirection,
    circleSize = 0.5,
    circleFill = 'black',
    lineCol = 1,
    extraBarbLength = -0.2,
    lwd = 1.2
  )
}


maps::map('state', 'oregon', fill = FALSE, col = 'gray80')
title("Wind Gusts on Sept. 7th at noon")

for ( station in stationList_OR ) {
  data <- 
    station$data %>%
    dplyr::filter(
      datetime == MazamaCoreUtils::parseDatetime(2020090712, timezone = "America/Los_Angeles")
    )
  knots <- data$maxGustSpeed * 1.944
  addWindBarbs(
    station$meta$longitude, 
    station$meta$latitude, 
    knots, 
    data$maxGustDirection,
    circleSize = 0.5,
    circleFill = 'black',
    lineCol = 1,
    extraBarbLength = -0.2,
    lwd = 1.2
  )
}


maps::map('state', 'oregon', fill = FALSE, col = 'gray80')
title("Wind Gusts on Sept. 7th at midnight")

for ( station in stationList_OR ) {
  data <- 
    station$data %>%
    dplyr::filter(
      datetime == MazamaCoreUtils::parseDatetime(2020090800, timezone = "America/Los_Angeles")
    )
  knots <- data$maxGustSpeed * 1.944
  addWindBarbs(
    station$meta$longitude, 
    station$meta$latitude, 
    knots, 
    data$maxGustDirection,
    circleSize = 0.5,
    circleFill = 'black',
    lineCol = 1,
    extraBarbLength = -0.2,
    lwd = 1.2
  )
}
```

## Wind shift time series plots

```{r windTimeseriesPlots, message = FALSE, echo = FALSE, fig.align = "center", fig.height = 10, fig.width = 10}

# Get data

orOBRR <- 
  wrcc_load(wrccID = "orOBRR", meta = oregonMeta, year = 2020) %>%
  raws_filterDate(20200904, 20200908)

orOGOO <- 
  wrcc_load(wrccID = "orOGOO", meta = oregonMeta, year = 2020) %>%
  raws_filterDate(20200904, 20200908)

orOBRRData <- orOBRR %>% raws_extractData()
orOGOOData <- orOGOO %>% raws_extractData()

# Create plots

orOBRRwindTimeseries <- windTimeseriesPlot(orOBRR)
orOGOOwindTimeseries <- windTimeseriesPlot(orOGOO)

orOBRRtimeseriesMultiplot <-
  timeseriesMultiplot(orOBRRData, pattern = c("humidity|temperature"), nrow = 2) + 
  ggplot2::ggtitle(sprintf("Temperature and Humidity in %s, %s", 
                           orOBRR$meta$wrccID, orOBRR$meta$siteName)) +
  ggplot2::xlab("Time") +
  ggplot2::ylab("Temperature (°C), Humidity (%)") +
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))

orOGOOtimeseriesMultiplot <-
  timeseriesMultiplot(orOGOOData, pattern = c("humidity|temperature"), nrow = 2) +
  ggplot2::ggtitle(sprintf("Temperature and Humidity in %s, %s", 
                           orOGOO$meta$wrccID, orOGOO$meta$siteName)) +
  ggplot2::xlab("Time") +
  ggplot2::ylab("Temperature (°C), Humidity (%)") +
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))

gridExtra::grid.arrange(orOBRRwindTimeseries, orOGOOwindTimeseries, orOBRRtimeseriesMultiplot, orOGOOtimeseriesMultiplot)
```

